{
 "title": "ColdCaseDashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Readouts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "u20_s2_temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u20_s2_temp\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])"
    }
   ]
  },
  {
   "title": "u79_s2_temp_b",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u79_s2_temp_b\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])"
    }
   ]
  },
  {
   "title": "u88_s2_temp_c",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u88_s2_temp_c\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "S4TempValues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-1m)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u16_s4_air_temp\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])\n|>drop(columns:[\"_field\",\"_measurement\",\"event_id\",\"deviceName\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-1m)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u76_s4_temp_b\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])\n|>drop(columns:[\"_field\",\"_measurement\",\"event_id\",\"deviceName\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "EEV",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u23_akv_od_pc\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])\n|>drop(columns:[\"_field\",\"_measurement\",\"event_id\",\"deviceName\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u82_akv_od_pc_b\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])\n|>drop(columns:[\"_field\",\"_measurement\",\"event_id\",\"deviceName\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u91_akv_od_pc_c\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])\n|>drop(columns:[\"_field\",\"_measurement\",\"event_id\",\"deviceName\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FoodTemperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u72_food_temp\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-30s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u20_s2_temp\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-30s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u79_s2_temp_b\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-30s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"u88_s2_temp_c\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MainSwitch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"r12_main_switch\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LowTempLimit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"a14_lowlim_air\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HighTempLimit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"a13_highlim_air\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DefrostMode",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 10 },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-2m)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"minus_def_start\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DefrostStopTemp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"d02_defstoptemp\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "StandbyMode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"minus_standby_mode\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DoorAlarm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"minus_door_alarm\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2Alarm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"minus_co2_alarm\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RefrigerantLeak",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"minus_refgleak\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HighTemp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"minus_high_temp_c\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LowTemp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "readings",
     "query": "from(bucket:\"my-bucket\")\n|>range(start:-3s)\n|>filter(fn:(r)=>r[\"resourceName\"]==\"minus_low_temp_c\")\n|>group(columns:[\"resourceName\"])\n|>sort(columns:[\"_time\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  }
 ]
}